Models/AnagraficaMOD.cs
namespace PoliziaMunicipale.Models
{
    public class AnagraficaMOD
    {
        public int ID { get; set; }
        public string? Nome { get; set; }
        public string? Cognome { get; set; }
        public string? Indirizzo { get; set; }
        public string? Città { get; set; }
        public string Cap { get; set; }
        public string? CodFisc { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace PoliziaMunicipale.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GuardieDBContext.cs
using Microsoft.EntityFrameworkCore;
using PoliziaMunicipale.Models;

namespace PoliziaMunicipale.Models
{
    public class GuardieDBContext : DbContext
    {
        public GuardieDBContext(DbContextOptions<GuardieDBContext> options) : base(options)
        {
        }

        public DbSet<AnagraficaMOD> Anagrafica { get; set; }

        public AnagraficaMOD? GetByIdAnagrafica(int idAnagrafica)
        {
            for (int i = 0; i < Anagrafica.Count(); i++)
            {
                var Persona = Anagrafica.ElementAt(i);
                if (Persona.ID == idAnagrafica)
                {
                    return Persona;
                }
            }
            return null;
        }

        public DbSet<TipoViolazioneMOD> TipiViolazione { get; set; }

        public TipoViolazioneMOD? GetByIdViolazione(int idViolazione)
        {
            for (int i = 0; i < TipiViolazione.Count(); i++)
            {
                var Violazione = TipiViolazione.ElementAt(i);
                if (Violazione.ID == idViolazione)
                {
                    return Violazione;
                }
            }
            return null;
        }

        public DbSet<VerbaleMOD> Verbale { get; set; }

        public VerbaleMOD? GetByIdVerbale(int idVerbale)
        {
            for (int i = 0; i < Verbale.Count(); i++)
            {
                var Multa = Verbale.ElementAt(i);
                if (Multa.ID == idVerbale)
                {
                    return Multa;
                }
            }
            return null;
        }




    }
}

Models/TipoViolazioneMOD.cs
namespace PoliziaMunicipale.Models
{
    public class TipoViolazioneMOD
    {
        public int ID { get; set; }
        public string Descrizione { get; set; }

    }
}

Models/VerbaleMOD.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PoliziaMunicipale.Models
{
    public class VerbaleMOD
    {
        public int ID { get; set; }

        public int IDViolazione { get; set; }

        public int IDAnagrafica { get; set; }

        public DateTime DataViolazione { get; set; }

        public string IndirizzoViolazione { get; set; }

        public string Nominativo_Agente { get; set; }

        public DateTime DataTrascrizioneVerbale { get; set; }

        public decimal Importo { get; set; }

        public int DecurtamentoPunti { get; set; }

        public bool Contestazione { get; set; }
    }
}

Controllers/AnagraficaController.cs
using Microsoft.AspNetCore.Mvc;
using PoliziaMunicipale.Models;
using System.Diagnostics;

namespace PoliziaMunicipale.Controllers
{
    public class AnagraficaController : Controller
    {
        private readonly ILogger<AnagraficaController> _logger;
        private readonly GuardieDBContext _context;

        public AnagraficaController(ILogger<AnagraficaController> logger, GuardieDBContext context)
        {
            _logger = logger;
            _context = context;
        }


        public IActionResult Index()
        {
            var Persone = _context.Anagrafica.ToList();
            return View(Persone);
        }

        public IActionResult AggiungiPersona(AnagraficaMOD Persona)
        {
            if (ModelState.IsValid)
            {
                _context.Anagrafica.Add(Persona);
                _context.SaveChanges();
                return RedirectToAction("Index", new { id = Persona.ID });
            }
            else
            {
                return View(Persona);
            }
        }

        [HttpPost]
        public IActionResult EliminaPersona(int ID)
        {
            var PersonaCancellata = _context.Anagrafica.Find(ID);
            if (PersonaCancellata != null)
            {
              
                _context.Anagrafica.Remove(PersonaCancellata);
                _context.SaveChanges();

                TempData["messaggio"] = $"Risorsa {PersonaCancellata.Nome} è stato eliminato";

                TempData["MessageSuccess"] = "Scarpe eliminate con successo!";
                return RedirectToAction("Index");
            }
            TempData["messaggioErrore"] = "C'è stato un errore nell'eliminazione";
            return RedirectToAction("Index");
        }

    }
}

Controllers/TipiViolazioneController.cs
using Microsoft.AspNetCore.Mvc;
using PoliziaMunicipale.Models;

namespace PoliziaMunicipale.Controllers
{
    public class TipiViolazioneController : Controller
    {
        private readonly ILogger<TipiViolazioneController> _logger;
        private readonly GuardieDBContext _context;

        public TipiViolazioneController(ILogger<TipiViolazioneController> logger, GuardieDBContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            var ListaViolazioni = _context.TipiViolazione.ToList();
            return View(ListaViolazioni);
        }

        public IActionResult AggiungiViolazione(TipoViolazioneMOD Violazione)
        {
            if (ModelState.IsValid)
            {
                _context.TipiViolazione.Add(Violazione);
                _context.SaveChanges();
                return RedirectToAction("Index", new { id = Violazione.ID });
            }
            else
            {
                return View(Violazione);
            }
        }

        [HttpPost]
        public IActionResult EliminaViolazione(int ID)
        {
            var ViolazioneCancellata = _context.TipiViolazione.Find(ID);
            if (ViolazioneCancellata != null)
            {

                _context.TipiViolazione.Remove(ViolazioneCancellata);
                _context.SaveChanges();         
                return RedirectToAction("Index");
            }
            TempData["messaggioErrore"] = "C'è stato un errore nell'eliminazione";
            return RedirectToAction("Index");
        }
    }

}

Controllers/VerbaleController.cs
using Microsoft.AspNetCore.Mvc;
using PoliziaMunicipale.Models;

namespace PoliziaMunicipale.Controllers
{
    public class VerbaleController : Controller
    {
        private readonly ILogger<VerbaleController> _logger;
        private readonly GuardieDBContext _context;

        public VerbaleController(ILogger<VerbaleController> logger, GuardieDBContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
        {
            var Verbali = _context.Verbale.ToList();
            return View(Verbali);
        }

        public IActionResult AggiungiVerbale(VerbaleMOD verbale)
        {
            if (ModelState.IsValid)
            {
                _context.Verbale.Add(verbale);
                _context.SaveChanges();
                return RedirectToAction("Index", new { id = verbale.ID });
            }
            else
            {
                return View(verbale);
            }
        }


    }
}

Views/Anagrafica/AggiungiPersona.cshtml
@{
    ViewData["Title"] = "Aggiungi Persona";
}

<div class="container">
    <h1 class="text-center">Aggiungi Persona</h1>
    <form asp-controller="Anagrafica" asp-action="AggiungiPersona" method="post">
        <div class="mb-3">
            <label for="Nome" class="form-label">Nome:</label>
            <input type="text" id="Nome" name="Nome" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="Cognome" class="form-label">Cognome:</label>
            <input type="text" id="Cognome" name="Cognome" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="Indirizzo" class="form-label">Indirizzo:</label>
            <input type="text" id="Indirizzo" name="Indirizzo" class="form-control">
        </div>

        <div class="mb-3">
            <label for="città" class="form-label">Città:</label>
            <input type="text" id="città" name="città" class="form-control">
        </div>

        <div class="mb-3">
            <label for="Cap" class="form-label">CAP:</label>
            <input type="text" id="Cap" name="Cap" class="form-control">
        </div>

        <div class="mb-3">
            <label for="CodFisc" class="form-label">Codice Fiscale:</label>
            <input type="text" id="CodFisc" name="CodFisc" class="form-control">
        </div>

        <button type="submit" class="btn btn-primary">Aggiungi</button>
    </form>
</div>

Views/Anagrafica/Index.cshtml
@{
    ViewData["Title"] = "Database Principale";
}

<div class="container">
    <h1 class="text-center">Anagrafica</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Cognome</th>
                    <th>Indirizzo</th>
                    <th>Città</th>
                    <th>Cap</th>
                    <th>Codice Fiscale</th>
                    <th>Elimina Persona</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var persona in Model)
                {
                    <tr>
                        <td>@persona.ID</td>
                        <td>@persona.Nome</td>
                        <td>@persona.Cognome</td>
                        <td>@persona.Indirizzo</td>
                        <td>@persona.Città</td>
                        <td>@persona.Cap</td>
                        <td>@persona.CodFisc</td>
                        <td>
                            <form asp-controller="Anagrafica" asp-action="EliminaPersona" method="post">
                                <input type="hidden" name="ID" value="@persona.ID" />
                                <button type="submit" class="btn btn-danger">Elimina</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Benvento Nel database della polizia Municipale!</h1>
</div>

Views/Home/PuntiDecurtatiPerTrasgressore.cshtml
@{
    ViewData["Title"] = "Punti Decurtati per Trasgressore";
}

<div class="container">
    <h1 class="text-center">Punti Decurtati per Trasgressore</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID Anagrafica</th>
                    <th>Totale Punti Decurtati</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.IDAnagrafica</td>
                        <td>@item.TotalePunti</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Home/VerbaliPerTrasgressore.cshtml
@{
    ViewData["Title"] = "Verbali per Trasgressore";
}

<h1 class="text-center">Verbali Per Trasgressore</h1>

<div class="container">    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID Anagrafica</th>
                    <th>Totale Verbali</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.IDAnagrafica</td>
                        <td>@item.TotaleVerbali</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Home/ViolazioniConImportoMaggioreDi400Euro.cshtml
@{
    ViewData["Title"] = "Violazioni con Importo Maggiore di 400 Euro";
}

<div class="container">
    <h1 class="text-center">Violazioni con Importo Maggiore di 400 Euro</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID Anagrafica</th>
                    <th>Importo</th>              
                    <th>Data Violazione</th>
                    <th>Punti Decurtati</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>                
                        <td>@item.IDAnagrafica</td>
                        <td>@item.Importo</td>
                        <td>@item.DataViolazione</td>
                        <td>@item.DecurtamentoPunti</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Home/ViolazioniConPiùDi10Punti.cshtml
@{
    ViewData["Title"] = "Violazioni con più di 10 Punti";
}

<div class="container">
    <h1 class="text-center">Violazioni con più di 10 Punti</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>               
                    <th>ID Anagrafica</th>
                    <th>Importo</th>
                    <th>Punti Decurtati</th>
                    <th>Data Violazione</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.IDAnagrafica</td>
                        <td>@item.Importo</td>
                        <td>@item.DecurtamentoPunti</td>
                        <td>@item.DataViolazione</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PoliziaMunicipale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PoliziaMunicipale.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PoliziaMunicipale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Filtri
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="VerbaliPerTrasgressore">Lista Anagrafica</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="PuntiDecurtatiPerTrasgressore">Punti Decurtati Per Trasgressore</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="ViolazioniConPiùDi10Punti">Violazioni con più di 10 punti</a></li>
                                <li><a class="dropdown-item" asp-controller="Home" asp-action="ViolazioniConImportoMaggioreDi400Euro">Violazione Con Importo Maggiore Di 400 Euro</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Verbali
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Anagrafica" asp-action="Index">Lista Anagrafica</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Anagrafica" asp-action="AggiungiPersona">Aggiungi Persona</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Violazioni
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="TipiViolazione" asp-action="Index">Lista Violazioni</a></li>
                                <li><a class="dropdown-item" asp-controller="TipiViolazione" asp-action="AggiungiViolazione">Aggiungi Violazioni</a></li>

                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Verbali
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Verbale" asp-action="Index">Lista Verbali</a></li>
                                <li><a class="dropdown-item" asp-controller="Verbale" asp-action="AggiungiVerbale">Aggiungi Verbale</a></li>

                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PoliziaMunicipale - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TipiViolazione/AggiungiViolazione.cshtml
@{
    ViewData["Title"] = "Aggiungi Violazione";
}

<div class="container">
    <h1 class="text-center">Aggiungi Persona</h1>
    <form asp-controller="TipiViolazione" asp-action="AggiungiViolazione" method="post">
        <div class="mb-3">
            <label for="Descrizione" class="form-label">Descrizione Violazione</label>
            <input type="text" id="Descrizione" name="Descrizione" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Aggiungi</button>
    </form>
</div>

Views/TipiViolazione/Index.cshtml
@{
    ViewData["Title"] = "Tipologie Di Violazioni";
}

<div class="container">
    <h1 class="text-center">Tipologie Di Violazioni</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tipo Violazione</th>
                    <th>Elimina Violazione</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var TipiViolazione in Model)
                {
                    <tr>
                        <td>@TipiViolazione.ID</td>
                        <td>@TipiViolazione.Descrizione</td>
                        <td>
                            <form asp-controller="TipiViolazione" asp-action="EliminaViolazione" method="post">
                                <input type="hidden" name="ID" value="@TipiViolazione.ID" />
                                <button type="submit" class="btn btn-danger">Elimina</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Verbale/AggiungiVerbale.cshtml
@{
    ViewData["Title"] = "Aggiungi Verbale";
}

<div class="container">
    <h1 class="text-center">Aggiungi Verbale</h1>
    <form asp-controller="Verbale" asp-action="AggiungiVerbale" method="post">
        <div class="mb-3">
            <label for="IDViolazione" class="form-label">ID Violazione:</label>
            <input type="text" id="IDViolazione" name="IDViolazione" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="IDAnagrafica" class="form-label">ID Anagrafica:</label>
            <input type="text" id="IDAnagrafica" name="IDAnagrafica" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="DataViolazione" class="form-label">Data Violazione:</label>
            <input type="date" id="DataViolazione" name="DataViolazione" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="IndirizzoViolazione" class="form-label">Indirizzo Violazione:</label>
            <input type="text" id="IndirizzoViolazione" name="IndirizzoViolazione" class="form-control">
        </div>

        <div class="mb-3">
            <label for="Nominativo_Agente" class="form-label">Nominativo Agente:</label>
            <input type="text" id="Nominativo_Agente" name="Nominativo_Agente" class="form-control">
        </div>

        <div class="mb-3">
            <label for="Importo" class="form-label">Importo:</label>
            <input type="number" id="Importo" name="Importo" class="form-control" step="0.01" required>
        </div>

        <div class="mb-3">
            <label for="DataTrascrizioneVerbale" class="form-label">Data trascrizione verbale:</label>
            <input type="date" id="DataTrascrizioneVerbale" name="DataTrascrizioneVerbale" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="DecurtamentoPunti" class="form-label">Punti Decurtati:</label>
            <input type="number" id="DecurtamentoPunti" name="DecurtamentoPunti" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="Contestazione" class="form-label">Contestazione:</label>
            <select id="Contestazione" name="Contestazione" class="form-control" required>
                <option value="">Seleziona</option>
                <option value="true">Sì</option>
                <option value="false">No</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Aggiungi</button>
    </form>
</div>

Views/Verbale/Index.cshtml
@{
    ViewData["Title"] = "Verbali";
}

<div class="container">
    <h1 class="text-center">Elenco Verbali</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>ID Violazione</th>
                    <th>ID Anagrafica</th>
                    <th>Data Violazione</th>
                    <th>Indirizzo Violazione</th>
                    <th>Nominativo Agente</th>
                    <th>Data Trascrizione Verbale</th>
                    <th>Importo</th>
                    <th>Decurtamento Punti</th>
                    <th>Contestazione</th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var Verbale in Model)
                {
                    <tr>
                        <td>@Verbale.ID</td>
                        <td>@Verbale.IDViolazione</td>
                        <td>@Verbale.IDAnagrafica</td>
                        <td>@Verbale.DataViolazione</td>
                        <td>@Verbale.IndirizzoViolazione</td>
                        <td>@Verbale.Nominativo_Agente</td>
                        <td>@Verbale.DataTrascrizioneVerbale</td>
                        <td>@Verbale.Importo</td>
                        <td>@Verbale.DecurtamentoPunti</td>
                        <td>@(Verbale.Contestazione ? "Contestata" : "Non Contestata")</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>